language: python
python:
 - "3.7"

# command to run tests
script:
 - python -m unittest us01_test
 - python -m unittest us02_test
 - python -m unittest us03_test
 - python -m unittest us04_test
 - python -m unittest us05_test
 - python -m unittest us07_test
 - python -m unittest US08_Test
 - python -m unittest US09_Test
